receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  filelog:
    include: [/var/log/flog/*.log]
    operators:
      - type: regex_parser
        regex: '^(?P<ip>\S+) \S+ \S+ \[(?P<timestamp>[^\]]+)\] "(?P<method>\S+) (?P<path>\S+) \S+" (?P<status>\d+) (?P<size>\d+) "(?P<referer>[^"]*)" "(?P<user_agent>[^"]*)"$'
        timestamp:
          parse_from: attributes.timestamp
          layout: '%d/%b/%Y:%H:%M:%S %z'

processors:
  batch:
    timeout: 5s
    send_batch_size: 1024
  resource:
    attributes:
      - key: deployment.environment
        value: ${env:DEPLOYMENT_ENV}
        action: upsert

exporters:
  debug:
    verbosity: ${env:DEBUG_VERBOSITY}
  datadog:
    api:
      key: ${env:DD_API_KEY}
      site: ${env:DD_SITE}

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: ${env:TRACES_EXPORTERS}
    metrics:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: ${env:METRICS_EXPORTERS}
    logs:
      receivers: [otlp, filelog]
      processors: [batch, resource]
      exporters: ${env:LOGS_EXPORTERS}
